### ISSUE TITLE
decorators

### ISSUE THREAD

**Issue by christopher-chandler** [nomisreual/TicTacToe#4]
https://github.com/nomisreual/TicTacToe/blob/6ee255a0fe00afcd5344a306be7115804121b89b/elements.py#L16
hey, can you explain to me why exatcly you used these decorators?

**Comment by nomisreual** [comment]
It is actually a bit of an overkill. That way I can _hide_ object properties defined in `__init__()`, but still access them via dot notation. Which makes it here mostly redundant. However, it is nice if you want to validate an input before updating the object attribute. Like this, you can easily incorporate validation logic within your classes. Now that I think about it, I could potentially use it more to validate user given input.


I hope that helped.

**Comment by christopher-chandler** [comment]
ah gotcha, I might keep them in my version, but sounds kinda cool! Thanks!
